1.	Simula cualquier matriz rectangular aleatoria A.

•	¿Cuál es el rango y la traza de A?
•	¿Cuál es el determinante de A?
•	¿Puedes invertir A? ¿Cómo?
•	¿Cómo están relacionados los autovalores y autovectores de A'A y AA'? ¿Qué diferencias interesantes puedes notar entre ambos?
•	Ver [https://sites.cs.ucsb.edu/~mturk/Papers/jcn.pdf]


In [ ]:
import numpy as np

# Paso 1: Generar una matriz rectangular aleatoria con dimensiones 3x5
rows = 3
cols = 5
A = np.random.rand(rows, cols)

# Paso 2: Imprimir la matriz generada
print("Matriz A:")
print(A)

# Paso 3: Calcular el rango de la matriz A
rank_A = np.linalg.matrix_rank(A)
print("Rango de A:", rank_A)

# Paso 4: Calcular la traza de la matriz A
trace_A = np.trace(A)
print("Traza de A:", trace_A)

# Paso 5: Calcular el determinante de la matriz A usando SVD
U, s, V = np.linalg.svd(A, full_matrices=False)
det_A = np.prod(s)
print("Determinante de A:", det_A)

# Paso 6: Intentar invertir la matriz A
try:
    inv_A = np.linalg.inv(A)
    print("La matriz A es invertible.")
except np.linalg.LinAlgError:
    print("La matriz A no es invertible.")

# Paso 7: Calcular los eigenvalores y eigenvectores de A'A y AA'
eigenvalues_A_transpose_A, eigenvectors_A_transpose_A = np.linalg.eig(A.T @ A)
eigenvalues_AA_transpose, eigenvectors_AA_transpose = np.linalg.eig(A @ A.T)

print("Eigenvalores de A'A:", eigenvalues_A_transpose_A)
print("Eigenvectores de A'A:", eigenvectors_A_transpose_A)
print("Eigenvalores de AA':", eigenvalues_AA_transpose)
print("Eigenvectores de AA':", eigenvectors_AA_transpose)


Matriz A:
[[0.60874254 0.2603815  0.52741226 0.56569879 0.38584922]
 [0.55886427 0.2327194  0.84194518 0.56351059 0.60368129]
 [0.78352735 0.71991008 0.55607433 0.00288054 0.39320619]]
Rango de A: 3
Traza de A: 1.3975362700956488
Determinante de A: 0.27138797750145105
La matriz A no es invertible.
Eigenvalores de A'A: [ 4.08487762e+00  4.09920250e-01  4.39848166e-02 -3.36249921e-17
  1.53129003e-16]
Eigenvectores de A'A: [[-0.55354117 -0.29240489 -0.47978286  0.32549229 -0.49998395]
 [-0.34299688 -0.62297207 -0.1135033  -0.37448248  0.55935626]
 [-0.55739901  0.17426072  0.57732885 -0.46663215 -0.35716324]
 [-0.32429725  0.69111163 -0.52609444 -0.21930651  0.28945291]
 [-0.40010366  0.135658    0.38319895  0.69855331  0.4751716 ]]
Eigenvalores de AA': [4.08487762 0.04398482 0.40992025]
Eigenvectores de AA': [[ 0.52351849  0.79571631 -0.30457173]
 [ 0.63467951 -0.60269984 -0.48366809]
 [ 0.56842792 -0.05990375  0.82054935]]


Los autovalores y autovectores de A'A y AA' están relacionados en el sentido de que comparten los mismos autovalores no negativos, pero difieren en las dimensiones de los autovectores y su interpretación geométrica en el espacio de columnas y filas de la matriz A. 